### ISSUE TITLE
MalformedPolicyDocumentException: An error occurred when calling the CreatePolicy operation: Actions/Condition can contain only one colon.

### ISSUE THREAD

**Issue by wobeng** [garnaat/kappa#111]
I'm getting 

```
MalformedPolicyDocumentException: An error occurred (MalformedPolicyDocument) when calling the CreatePolicy operation: Actions/Condition can contain only one colon.
-> creating role kappa-ca-gitub_master
-> role already exists
-> function configuration has not changed
-> updating function kappa-ca-gitub
-> function unchanged

``` 

with config below. What am I doing wrong?

```
name: kappa
environments:
  master:
    profile: kappa
    region: us-east-1
    policy:
      resources:
        - arn: arn:aws:logs:*:*:*
          actions:
            - "*"
        - arn: arn:aws:codebuild:*
          actions:
            - "codebuild:StartBuild"
            - "codebuild:StopBuild"
            - "codebuild:BatchGet*"
            - "codebuild:Get*"
            - "codebuild:List*"
    event_sources:
      - arn: arn:aws:sns:us-east-1:blah:blah
lambda:
  description: aws lamdba function to execute codebuild
  handler: main.handler
  runtime: python2.7
  memory_size: 128
  timeout: 3
  log_retention_policy: 1
```

**Comment by wobeng** [comment]
Answer is 

```
name: kappa
environments:
  master:
    profile: kappa
    region: us-east-1
    policy:
      resources:
        - arn: arn:aws:logs:*:*:*
          actions:
            - "*"
        - arn: arn:aws:codebuild:*
          actions:
            - "StartBuild"
            - "StopBuild"
            - "BatchGet*"
            - "Get*"
            - "List*"
    event_sources:
      - arn: arn:aws:sns:us-east-1:blah:blah
lambda:
  description: aws lamdba function to execute codebuild
  handler: main.handler
  runtime: python2.7
  memory_size: 128
  timeout: 3
  log_retention_policy: 1

```
