### ISSUE TITLE
Unable to update alias

### ISSUE THREAD

**Issue by wobeng** [garnaat/kappa#113]
I'm getting the error below:

```
[Container] 2017/02/22 22:12:14 deploying
[Container] 2017/02/22 22:12:14 -> deploying policy kappa-ca-lambda-notify_master
[Container] 2017/02/22 22:12:14 -> creating role kappa-ca-lambda-notify_master
[Container] 2017/02/22 22:12:14 -> role already exists
[Container] 2017/02/22 22:12:14 -> updating configuration for kappa-ca-lambda-notify
[Container] 2017/02/22 22:12:14 -> updating function kappa-ca-lambda-notify
[Container] 2017/02/22 22:12:14 -> uploading new function zipfile kappa-ca-lambda-notify.zip
[Container] 2017/02/22 22:12:15 -> Unable to update alias
[Container] 2017/02/22 22:12:15 Traceback (most recent call last):
[Container] 2017/02/22 22:12:15 File "/tmp/src832689071/src/venv/lib/python2.7/site-packages/kappa/function.py", line 353, in update_alias
[Container] 2017/02/22 22:12:15 Name=name)
[Container] 2017/02/22 22:12:15 File "/tmp/src832689071/src/venv/lib/python2.7/site-packages/kappa/awsclient.py", line 86, in call
[Container] 2017/02/22 22:12:15 data = op(**kwargs)
[Container] 2017/02/22 22:12:15 File "/tmp/src832689071/src/venv/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
[Container] 2017/02/22 22:12:15 return self._make_api_call(operation_name, kwargs)
[Container] 2017/02/22 22:12:15 File "/tmp/src832689071/src/venv/lib/python2.7/site-packages/botocore/client.py", line 543, in _make_api_call
[Container] 2017/02/22 22:12:15 raise error_class(parsed_response, operation_name)
[Container] 2017/02/22 22:12:15 ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the UpdateAlias operation: Alias not found: arn:aws:lambda:us-east-1:blah:function:kappa-ca-lambda-notify:master
[Container] 2017/02/22 22:12:15 done
```

With the config below

```

name: kappa-ca-lambda-notify
environments:
  develop:
    region: us-east-1
    policy:
      resources:
        - arn: arn:aws:logs:*:*:*
          actions:
            - "*"
        - arn: arn:aws:ses:*:*:*
          actions:
            - "*"
    event_sources:
      - arn: arn:aws:sns:us-east-1:blah:blah
  stage:
    region: us-east-1
    policy:
      resources:
        - arn: arn:aws:logs:*:*:*
          actions:
            - "*"
        - arn: arn:aws:ses:*:*:*
          actions:
            - "*"
    event_sources:
      - arn: arn:aws:sns:us-east-1:blah:blah
  master:
    region: us-east-1
    policy:
      resources:
        - arn: arn:aws:logs:*:*:*
          actions:
            - "*"
        - arn: arn:aws:ses:*:*:*
          actions:
            - "*"
    event_sources:
      - arn: arn:aws:sns:us-east-1:blah:blah
lambda:
  description: aws lamdba function to send emails
  handler: main.handler
  runtime: python2.7
  memory_size: 128
  timeout: 3
  log_retention_policy: 1

```
