### ISSUE TITLE
nodejs function deployment hangs

### ISSUE THREAD

**Issue by leoamigood** [garnaat/kappa#121]
Nodejs lambda function deployment hangs. Same, but python2.7 works just fine.

Role gets created, but *DEBUG - Role is not ready, waiting*

kappa.yml

```
---
name: name-goes-here
source: .
environments:
  dev:
    profile: testing
    region: us-east-1
    policy:
      resources:
        - arn: arn:aws:s3:::*
          actions:
          - "*"
        - arn: arn:aws:logs:*:*:*
          actions:
          - "*"
    event_sources:
      -
        arn: arn:aws:s3:::name-goes-here-bucket
        events:
          - s3:ObjectCreated:*
lambda:
  description: Name Goes Here
  handler: handler.callme
  runtime: nodejs
  memory_size: 128
  timeout: 60
  mode: event
  permissions:
    -
      statement_id: s3_invoke
      action: lambda:invokeFunction
      principal: s3.amazonaws.com
      arn: arn:aws:s3:::*
```
