### ISSUE TITLE
deploy creates zip wrongly with folders

### ISSUE THREAD

**Issue by teebu** [garnaat/kappa#6]
There is a bug when it creates a zip with a path in the settings. Amazon wants the contents of the zip, not the folder zipped. 

See here: http://docs.aws.amazon.com/lambda/latest/dg/walkthrough-s3-events-adminuser-create-test-function-create-function.html

For example:

myfolder
|-myfunc.js
|-node_modules
|--morestuff

zip should look like:
myfunc.js
|-node_modules
|--morestuff

**Comment by garnaat** [comment]
How are you specifying the ``path`` value in the config file?

**Comment by teebu** [comment]
I tried both
  path: s3resize/
and 
  path: s3resize

I feel like i should mention I'm on windows.

**Comment by mediavrog** [comment]
Same here. Tried with the default setup, and amazon would not find the module "AutoStart"

```
autoStart/AutoStart.js
```
with config
```
lambda:
  name: AutoStartLalala
  zipfile_name: AutoStart.zip
  description: Start ....
  path: autoStart/
  handler: AutoStart.handler
  runtime: nodejs
  memory_size: 128
  timeout: 3
  mode: event
  test_data: sample_event.json
  event_sources:
    -
      arn: arn:aws:s3:::bucketName
      events:
        - s3:ObjectCreated:*
```

after manually zipping only the contents of the `autoStart` folder and reuploading, it worked.
