### ISSUE TITLE
S3 Event Source should add permission for S3 bucket to invoke function

### ISSUE THREAD

**Issue by olabhrad** [garnaat/kappa#87]
Currently an S3 event source does not work out of the box as you would expect:

```
    event_sources:
      - arn: arn:aws:s3:::<bucket>
        events:
          - s3:ObjectCreated:*
        key_filters:
          - type: prefix
            value: <prefix>/
          - type: suffix
            value: <suffix>
```

The issue is that the S3 bucket does not have permissions to invoke the function. The workaround is to add the permission in the "permissions" section under "lambda":

```
lambda:
  description: <description>
  handler: <function>.lambda_handler
  runtime: python2.7
  memory_size: 128
  timeout: 300
  permissions:
    - action: lambda:invokeFunction
      principal: s3.amazonaws.com
      SourceArn: arn: arn:aws:s3:::<bucket>
```
This permission should automatically be added in the S3 event source add function similar to how the cloudwatch event source add function handles adding the relevant permission:

e.g. something like

```
               response = self._lambda.call('add_permission',
                                             FunctionName=function.name,
                                             StatementId=str(uuid.uuid4()),
                                             Action='lambda:InvokeFunction',
                                             Principal='s3.amazonaws.com',
                                             SourceArn=self._get_bucket_name())
```
